// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udonteycxkugacnnxbnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb250ZXljeGt1Z2Fjbm54Ym5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDMwNTksImV4cCI6MjA3Mjk3OTA1OX0.atvz1KNlQgetEogdBC4qHCiQVoDqUf9tBrLkcDLoZCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});